### PR TITLE
Python 3.9+ support

### PR DESCRIPTION
**Pull request by nyukhalov**
python-OBD does not work with python 3.9+ because the old `pint` version uses deprecated collections API:

```python
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

The issue was fixed in a newer `pint`.
This change, however, sets the minimum supported python version to 3.8, according to pint's README.

### CODE REVIEW

**Comment by alistair23** [comment]
Doesn't this mean it won't work on Python versions below 3.9? We are still testing versions below that in the CI

**Comment by nyukhalov** [comment]
Hi @alistair23, `pint`'s README says it runs on python 3.8+.

**Comment by nyukhalov** [comment]
Makes sense.
Is there anything I can help you with to get it done?

**Comment by nyukhalov** [comment]
Alternatively, I could try to find a `pint`'s version that contains the fix, but did't drop support for older python versions.
Having a proper build matrix on CI would help a lot with testing such a change.

**Comment by alistair23** [comment]
It would be great if you could write the GitHub CI! :)

I think using a earlier version of pint with more versions supported would also be great

**Comment by nyukhalov** [comment]
Sure, added a definition for a CI pipeline using Github Actions: https://github.com/brendan-w/python-OBD/pull/240

**Comment by pcakhilnadh** [comment]
Does it support py 3.10.x ?

**Review by alistair23 — APPROVED** [review]
